apiVersion: restore.restore.elastic.co/v1
kind: RestoreTask
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: restoretask-sample
spec:
  # TODO(user): Add fields here
