# This rule is not used by the project controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to restore.restore.elastic.co resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: restoretask-viewer-role
rules:
- apiGroups:
  - restore.restore.elastic.co
  resources:
  - restoretasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - restore.restore.elastic.co
  resources:
  - restoretasks/status
  verbs:
  - get
